package com.example.divvy.ui.auth.Views

import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.divvy.components.AuthTextField
import com.example.divvy.ui.auth.ViewModels.AuthFlowViewModel

@Composable fun LaunchScreen(onCreateAccount: () -> Unit, onLogin: () -> Unit) { Column(Modifier.fillMaxSize().background(AuthGradientBackground()).padding(24.dp), verticalArrangement = Arrangement.Bottom) { Text("Welcome to Divvy", fontSize = 26.sp, fontWeight = FontWeight.Bold, color = Color.White); Spacer(Modifier.height(8.dp)); Text("Stop chasing. Start settling.\n", fontSize = 14.sp, color = Color(0xFFE6E0F5), lineHeight = 20.sp); Spacer(Modifier.height(24.dp)); AuthPrimaryButton("Create an account", Modifier.fillMaxWidth(), onClick = onCreateAccount); Spacer(Modifier.height(12.dp)); Row(Modifier.fillMaxWidth(), Arrangement.Center) { Text("Already have an account? ", color = Color(0xFFE6E0F5), fontSize = 13.sp); Text("Log in", color = Color.White, fontSize = 13.sp, fontWeight = FontWeight.SemiBold, modifier = Modifier.clickable { onLogin() }) }; Spacer(Modifier.height(12.dp)) } }

@Composable fun CreateStartScreen(onBack: () -> Unit, onPhone: () -> Unit, onGoogle: () -> Unit) { Column(Modifier.fillMaxSize().background(AuthBackground).padding(24.dp), horizontalAlignment = Alignment.CenterHorizontally) { AuthTopBar("Create new account", onBack); Spacer(Modifier.height(12.dp)); Text("Begin with creating new free account.", textAlign = TextAlign.Center, color = MutedText, lineHeight = 20.sp); Spacer(Modifier.height(28.dp)); AuthPrimaryButton("Continue with phone", Modifier.fillMaxWidth(), onClick = onPhone); Spacer(Modifier.height(16.dp)); Text("or", color = MutedText); Spacer(Modifier.height(16.dp)); AuthOutlinedButton("Continue with Google", Modifier.fillMaxWidth(), onClick = onGoogle); Spacer(Modifier.weight(1f)); Text("By using Divvy, you agree to the", color = MutedText, fontSize = 12.sp); Text("Terms and Privacy Policy.", color = Color(0xFF1F2937), fontSize = 12.sp, fontWeight = FontWeight.SemiBold) } }

@Composable fun CreatePhoneScreen(viewModel: AuthFlowViewModel, onBack: () -> Unit, onNext: () -> Unit) { val state by viewModel.state.collectAsState(); Column(Modifier.fillMaxSize().background(AuthBackground).padding(24.dp).verticalScroll(rememberScrollState()), horizontalAlignment = Alignment.CenterHorizontally) { AuthTopBar("Add your phone 1/3", onBack); StepIndicator(1); Spacer(Modifier.height(16.dp)); Text("We'll text you a 6-digit code to verify.", textAlign = TextAlign.Center, color = MutedText); Spacer(Modifier.height(20.dp)); PhoneNumberField(state.countryCode, state.countryFlag, state.phoneDigits, viewModel::updateCountryOption, viewModel::updatePhoneDigits, Modifier.fillMaxWidth()); Spacer(Modifier.height(16.dp)); AuthPrimaryButton(if (state.isLoading) "Sending..." else "Send code", Modifier.fillMaxWidth(), !state.isLoading) { viewModel.sendPhoneOtp(true, onNext) }; if (state.errorMessage != null) { Spacer(Modifier.height(10.dp)); Text(state.errorMessage ?: "", color = Color(0xFFB42318), fontSize = 12.sp) }; Spacer(Modifier.weight(1f)); Text("By using Divvy, you agree to the", color = MutedText, fontSize = 12.sp); Text("Terms and Privacy Policy.", color = Color(0xFF1F2937), fontSize = 12.sp, fontWeight = FontWeight.SemiBold) } }

@Composable fun VerifyPhoneScreen(viewModel: AuthFlowViewModel, onBack: () -> Unit, onNext: () -> Unit, onChangePhone: () -> Unit) { val state by viewModel.state.collectAsState(); Column(Modifier.fillMaxSize().background(AuthBackground).padding(24.dp).verticalScroll(rememberScrollState()), horizontalAlignment = Alignment.CenterHorizontally) { AuthTopBar("Verify your phone 2/3", onBack); StepIndicator(2); Spacer(Modifier.height(16.dp)); Text("We just sent 6-digit code to\n${formatPhoneNumber(state.countryCode, state.phoneDigits)}, enter it below:", textAlign = TextAlign.Center, color = MutedText); Spacer(Modifier.height(16.dp)); OtpInputRow(state.otp, onValueChange = viewModel::updateOtp); Spacer(Modifier.height(16.dp)); AuthPrimaryButton(if (state.isLoading) "Verifying..." else "Verify phone", Modifier.fillMaxWidth(), !state.isLoading) { viewModel.verifyPhoneOtp(onNext) }; Spacer(Modifier.height(10.dp)); Text("Wrong number? Send to different phone", color = Color(0xFF1F2937), fontSize = 12.sp, modifier = Modifier.clickable { onChangePhone() }); if (state.errorMessage != null) { Spacer(Modifier.height(10.dp)); Text(state.errorMessage ?: "", color = Color(0xFFB42318), fontSize = 12.sp) }; Spacer(Modifier.weight(1f)); Text("By using Divvy, you agree to the", color = MutedText, fontSize = 12.sp); Text("Terms and Privacy Policy.", color = Color(0xFF1F2937), fontSize = 12.sp, fontWeight = FontWeight.SemiBold) } }

@Composable fun NameScreen(viewModel: AuthFlowViewModel, onBack: () -> Unit, onDone: () -> Unit) { val state by viewModel.state.collectAsState(); LaunchedEffect(Unit) { viewModel.prefillProfileEmail() }; Column(Modifier.fillMaxSize().background(AuthBackground).padding(24.dp).verticalScroll(rememberScrollState()), horizontalAlignment = Alignment.CenterHorizontally) { AuthTopBar("Tell us about you", onBack); StepIndicator(3); Spacer(Modifier.height(12.dp)); Text("Add your phone, email, and name so friends can find you.", color = MutedText, textAlign = TextAlign.Center); Spacer(Modifier.height(20.dp)); PhoneNumberField(state.countryCode, state.countryFlag, state.phoneDigits, viewModel::updateCountryOption, viewModel::updatePhoneDigits, Modifier.fillMaxWidth()); Spacer(Modifier.height(12.dp)); AuthTextField(state.profileEmail, viewModel::updateProfileEmail, "Email", Modifier.fillMaxWidth(), KeyboardType.Email); Spacer(Modifier.height(12.dp)); AuthTextField(state.firstName, viewModel::updateFirstName, "First name", Modifier.fillMaxWidth()); Spacer(Modifier.height(12.dp)); AuthTextField(state.lastName, viewModel::updateLastName, "Last name", Modifier.fillMaxWidth()); Spacer(Modifier.height(18.dp)); AuthPrimaryButton(if (state.isLoading) "Saving..." else "Continue", Modifier.fillMaxWidth(), !state.isLoading) { viewModel.saveProfile(onDone) }; if (state.errorMessage != null) { Spacer(Modifier.height(10.dp)); Text(state.errorMessage ?: "", color = Color(0xFFB42318), fontSize = 12.sp) } } }

@Composable fun LoginStartScreen(onBack: () -> Unit, onPhone: () -> Unit, onGoogle: () -> Unit) { Column(Modifier.fillMaxSize().background(AuthBackground).padding(24.dp), horizontalAlignment = Alignment.CenterHorizontally) { AuthTopBar("Log into account", onBack); Spacer(Modifier.height(8.dp)); Text("Welcome back!", color = MutedText); Text("It's time to divvy up", color = MutedText); Spacer(Modifier.height(24.dp)); AuthPrimaryButton("Continue with phone", Modifier.fillMaxWidth(), onClick = onPhone); Spacer(Modifier.height(14.dp)); Text("or", color = MutedText); Spacer(Modifier.height(14.dp)); AuthOutlinedButton("Continue with Google", Modifier.fillMaxWidth(), onClick = onGoogle); Spacer(Modifier.weight(1f)); Text("By using Divvy, you agree to the", color = MutedText, fontSize = 12.sp); Text("Terms and Privacy Policy.", color = Color(0xFF1F2937), fontSize = 12.sp, fontWeight = FontWeight.SemiBold) } }

@Composable fun LoginPhoneScreen(viewModel: AuthFlowViewModel, onBack: () -> Unit, onNext: () -> Unit) { val state by viewModel.state.collectAsState(); Column(Modifier.fillMaxSize().background(AuthBackground).padding(24.dp).verticalScroll(rememberScrollState()), horizontalAlignment = Alignment.CenterHorizontally) { AuthTopBar("Log into account", onBack); Spacer(Modifier.height(12.dp)); Text("Enter your phone number to continue.", color = MutedText); Spacer(Modifier.height(20.dp)); PhoneNumberField(state.countryCode, state.countryFlag, state.phoneDigits, viewModel::updateCountryOption, viewModel::updatePhoneDigits, Modifier.fillMaxWidth()); Spacer(Modifier.height(16.dp)); AuthPrimaryButton(if (state.isLoading) "Sending..." else "Send code", Modifier.fillMaxWidth(), !state.isLoading) { viewModel.sendPhoneOtp(false, onNext) }; if (state.errorMessage != null) { Spacer(Modifier.height(10.dp)); Text(state.errorMessage ?: "", color = Color(0xFFB42318), fontSize = 12.sp) } } }

@Composable fun VerifyPhoneLoginScreen(viewModel: AuthFlowViewModel, onBack: () -> Unit, onLogin: () -> Unit, onChangePhone: () -> Unit) { val state by viewModel.state.collectAsState(); Column(Modifier.fillMaxSize().background(AuthBackground).padding(24.dp).verticalScroll(rememberScrollState()), horizontalAlignment = Alignment.CenterHorizontally) { AuthTopBar("Enter verification code", onBack); Spacer(Modifier.height(16.dp)); Text("We just sent 6-digit code to\n${formatPhoneNumber(state.countryCode, state.phoneDigits)}", textAlign = TextAlign.Center, color = MutedText); Spacer(Modifier.height(16.dp)); OtpInputRow(state.otp, onValueChange = viewModel::updateOtp); Spacer(Modifier.height(16.dp)); AuthPrimaryButton(if (state.isLoading) "Verifying..." else "Verify & log in", Modifier.fillMaxWidth(), !state.isLoading) { viewModel.verifyPhoneOtp(onLogin) }; Spacer(Modifier.height(10.dp)); Text("Wrong number? Send to different phone", color = Color(0xFF1F2937), fontSize = 12.sp, modifier = Modifier.clickable { onChangePhone() }); if (state.errorMessage != null) { Spacer(Modifier.height(10.dp)); Text(state.errorMessage ?: "", color = Color(0xFFB42318), fontSize = 12.sp) } } }
